# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_nanotube.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_NanoTube(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(384, 207)
        Form.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.BuildSingleWall = QtWidgets.QWidget(Form)
        self.BuildSingleWall.setAutoFillBackground(False)
        self.BuildSingleWall.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.BuildSingleWall.setObjectName("BuildSingleWall")
        self.label_chirality_N = QtWidgets.QLabel(self.BuildSingleWall)
        self.label_chirality_N.setGeometry(QtCore.QRect(11, 14, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_chirality_N.setFont(font)
        self.label_chirality_N.setObjectName("label_chirality_N")
        self.label_repeat_units = QtWidgets.QLabel(self.BuildSingleWall)
        self.label_repeat_units.setGeometry(QtCore.QRect(220, 56, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_repeat_units.setFont(font)
        self.label_repeat_units.setObjectName("label_repeat_units")
        self.label_bond_length = QtWidgets.QLabel(self.BuildSingleWall)
        self.label_bond_length.setGeometry(QtCore.QRect(10, 60, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_bond_length.setFont(font)
        self.label_bond_length.setObjectName("label_bond_length")
        self.label_type_nanotube = QtWidgets.QLabel(self.BuildSingleWall)
        self.label_type_nanotube.setGeometry(QtCore.QRect(220, 15, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_type_nanotube.setFont(font)
        self.label_type_nanotube.setObjectName("label_type_nanotube")
        self.comboBox_type_nanotube = QtWidgets.QComboBox(self.BuildSingleWall)
        self.comboBox_type_nanotube.setGeometry(QtCore.QRect(260, 15, 101, 21))
        self.comboBox_type_nanotube.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_type_nanotube.setObjectName("comboBox_type_nanotube")
        self.comboBox_type_nanotube.addItem("")
        self.comboBox_type_nanotube.addItem("")
        self.comboBox_type_nanotube.addItem("")
        self.comboBox_type_nanotube.addItem("")
        self.comboBox_type_nanotube.addItem("")
        self.comboBox_type_nanotube.addItem("")
        self.lineEdit_bond_length = QtWidgets.QLineEdit(self.BuildSingleWall)
        self.lineEdit_bond_length.setGeometry(QtCore.QRect(129, 54, 71, 31))
        self.lineEdit_bond_length.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_bond_length.setClearButtonEnabled(True)
        self.lineEdit_bond_length.setObjectName("lineEdit_bond_length")
        self.pushButton_build_nanotube = QtWidgets.QPushButton(self.BuildSingleWall)
        self.pushButton_build_nanotube.setGeometry(QtCore.QRect(217, 110, 61, 31))
        self.pushButton_build_nanotube.setObjectName("pushButton_build_nanotube")
        self.label_chirality_M = QtWidgets.QLabel(self.BuildSingleWall)
        self.label_chirality_M.setGeometry(QtCore.QRect(121, 15, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_chirality_M.setFont(font)
        self.label_chirality_M.setObjectName("label_chirality_M")
        self.spinBox_chirality_N = QtWidgets.QSpinBox(self.BuildSingleWall)
        self.spinBox_chirality_N.setGeometry(QtCore.QRect(36, 10, 51, 31))
        self.spinBox_chirality_N.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_chirality_N.setProperty("value", 1)
        self.spinBox_chirality_N.setObjectName("spinBox_chirality_N")
        self.spinBox_chirality_M = QtWidgets.QSpinBox(self.BuildSingleWall)
        self.spinBox_chirality_M.setGeometry(QtCore.QRect(147, 10, 51, 31))
        self.spinBox_chirality_M.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_chirality_M.setProperty("value", 1)
        self.spinBox_chirality_M.setObjectName("spinBox_chirality_M")
        self.spinBox_repeat_units = QtWidgets.QSpinBox(self.BuildSingleWall)
        self.spinBox_repeat_units.setGeometry(QtCore.QRect(310, 50, 51, 31))
        self.spinBox_repeat_units.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_repeat_units.setMinimum(1)
        self.spinBox_repeat_units.setObjectName("spinBox_repeat_units")
        self.pushButton_help_build_nanotube = QtWidgets.QPushButton(self.BuildSingleWall)
        self.pushButton_help_build_nanotube.setGeometry(QtCore.QRect(298, 110, 61, 31))
        self.pushButton_help_build_nanotube.setObjectName("pushButton_help_build_nanotube")
        self.label_7 = QtWidgets.QLabel(self.BuildSingleWall)
        self.label_7.setGeometry(QtCore.QRect(10, 162, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_diameter_nanotube = QtWidgets.QLineEdit(self.BuildSingleWall)
        self.lineEdit_diameter_nanotube.setGeometry(QtCore.QRect(100, 162, 51, 21))
        self.lineEdit_diameter_nanotube.setAcceptDrops(False)
        self.lineEdit_diameter_nanotube.setStyleSheet("")
        self.lineEdit_diameter_nanotube.setFrame(False)
        self.lineEdit_diameter_nanotube.setClearButtonEnabled(True)
        self.lineEdit_diameter_nanotube.setObjectName("lineEdit_diameter_nanotube")
        self.label_8 = QtWidgets.QLabel(self.BuildSingleWall)
        self.label_8.setGeometry(QtCore.QRect(10, 100, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.comboBox_type_nanotube_2 = QtWidgets.QComboBox(self.BuildSingleWall)
        self.comboBox_type_nanotube_2.setGeometry(QtCore.QRect(141, 94, 61, 31))
        self.comboBox_type_nanotube_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_type_nanotube_2.setObjectName("comboBox_type_nanotube_2")
        self.comboBox_type_nanotube_2.addItem("")
        self.comboBox_type_nanotube_2.addItem("")
        self.comboBox_type_nanotube_2.addItem("")
        self.label_9 = QtWidgets.QLabel(self.BuildSingleWall)
        self.label_9.setGeometry(QtCore.QRect(10, 135, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_length_nanotube = QtWidgets.QLabel(self.BuildSingleWall)
        self.label_length_nanotube.setGeometry(QtCore.QRect(157, 162, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_length_nanotube.setFont(font)
        self.label_length_nanotube.setObjectName("label_length_nanotube")
        self.lineEdit_length_nanotube = QtWidgets.QLineEdit(self.BuildSingleWall)
        self.lineEdit_length_nanotube.setGeometry(QtCore.QRect(227, 162, 51, 21))
        self.lineEdit_length_nanotube.setAcceptDrops(False)
        self.lineEdit_length_nanotube.setStyleSheet("")
        self.lineEdit_length_nanotube.setFrame(False)
        self.lineEdit_length_nanotube.setClearButtonEnabled(True)
        self.lineEdit_length_nanotube.setObjectName("lineEdit_length_nanotube")
        self.verticalLayout.addWidget(self.BuildSingleWall)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_chirality_N.setText(_translate("Form", "N:"))
        self.label_repeat_units.setText(_translate("Form", "Repeat units:"))
        self.label_bond_length.setText(_translate("Form", "Bond length (Å):"))
        self.label_type_nanotube.setText(_translate("Form", "Type:"))
        self.comboBox_type_nanotube.setItemText(0, _translate("Form", "C - C"))
        self.comboBox_type_nanotube.setItemText(1, _translate("Form", "B - N"))
        self.comboBox_type_nanotube.setItemText(2, _translate("Form", "Ga - N"))
        self.comboBox_type_nanotube.setItemText(3, _translate("Form", "Al - N"))
        self.comboBox_type_nanotube.setItemText(4, _translate("Form", "Al - P"))
        self.comboBox_type_nanotube.setItemText(5, _translate("Form", "Ga - P"))
        self.pushButton_build_nanotube.setText(_translate("Form", "Build"))
        self.label_chirality_M.setText(_translate("Form", "M:"))
        self.pushButton_help_build_nanotube.setText(_translate("Form", "Help"))
        self.label_7.setText(_translate("Form", "Diameter (Å):"))
        self.label_8.setText(_translate("Form", "Hydrogen termination:"))
        self.comboBox_type_nanotube_2.setItemText(0, _translate("Form", "None"))
        self.comboBox_type_nanotube_2.setItemText(1, _translate("Form", "One ends"))
        self.comboBox_type_nanotube_2.setItemText(2, _translate("Form", "Both ends"))
        self.label_9.setText(_translate("Form", "Nanotube properties"))
        self.label_length_nanotube.setText(_translate("Form", "Length (Å):"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_NanoTube()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

