# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_SWNT.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form_SWNT(object):
    def setupUi(self, Form_SWNT):
        Form_SWNT.setObjectName("Form_SWNT")
        Form_SWNT.resize(384, 208)
        Form_SWNT.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_SWNT)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SWNT = QtWidgets.QWidget(Form_SWNT)
        self.SWNT.setAutoFillBackground(False)
        self.SWNT.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.SWNT.setObjectName("SWNT")
        self.label_chirality_N_SWNT = QtWidgets.QLabel(self.SWNT)
        self.label_chirality_N_SWNT.setGeometry(QtCore.QRect(11, 14, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_chirality_N_SWNT.setFont(font)
        self.label_chirality_N_SWNT.setObjectName("label_chirality_N_SWNT")
        self.label_repeat_units_SWNT = QtWidgets.QLabel(self.SWNT)
        self.label_repeat_units_SWNT.setGeometry(QtCore.QRect(220, 56, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_repeat_units_SWNT.setFont(font)
        self.label_repeat_units_SWNT.setObjectName("label_repeat_units_SWNT")
        self.label_bond_length_SWNT = QtWidgets.QLabel(self.SWNT)
        self.label_bond_length_SWNT.setGeometry(QtCore.QRect(10, 60, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_bond_length_SWNT.setFont(font)
        self.label_bond_length_SWNT.setObjectName("label_bond_length_SWNT")
        self.label_type_SWNT = QtWidgets.QLabel(self.SWNT)
        self.label_type_SWNT.setGeometry(QtCore.QRect(220, 15, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_type_SWNT.setFont(font)
        self.label_type_SWNT.setObjectName("label_type_SWNT")
        self.comboBox_type_SWNT = QtWidgets.QComboBox(self.SWNT)
        self.comboBox_type_SWNT.setGeometry(QtCore.QRect(260, 15, 101, 21))
        self.comboBox_type_SWNT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_type_SWNT.setObjectName("comboBox_type_SWNT")
        self.comboBox_type_SWNT.addItem("")
        self.comboBox_type_SWNT.addItem("")
        self.comboBox_type_SWNT.addItem("")
        self.comboBox_type_SWNT.addItem("")
        self.comboBox_type_SWNT.addItem("")
        self.comboBox_type_SWNT.addItem("")
        self.lineEdit_bond_length_SWNT = QtWidgets.QLineEdit(self.SWNT)
        self.lineEdit_bond_length_SWNT.setGeometry(QtCore.QRect(129, 54, 71, 31))
        self.lineEdit_bond_length_SWNT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_bond_length_SWNT.setClearButtonEnabled(False)
        self.lineEdit_bond_length_SWNT.setObjectName("lineEdit_bond_length_SWNT")
        self.pushButton_build_SWNT = QtWidgets.QPushButton(self.SWNT)
        self.pushButton_build_SWNT.setGeometry(QtCore.QRect(217, 110, 61, 31))
        self.pushButton_build_SWNT.setObjectName("pushButton_build_SWNT")
        self.label_chirality_M_SWNT = QtWidgets.QLabel(self.SWNT)
        self.label_chirality_M_SWNT.setGeometry(QtCore.QRect(121, 15, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_chirality_M_SWNT.setFont(font)
        self.label_chirality_M_SWNT.setObjectName("label_chirality_M_SWNT")
        self.spinBox_chirality_N_SWNT = QtWidgets.QSpinBox(self.SWNT)
        self.spinBox_chirality_N_SWNT.setGeometry(QtCore.QRect(36, 10, 51, 31))
        self.spinBox_chirality_N_SWNT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_chirality_N_SWNT.setProperty("value", 1)
        self.spinBox_chirality_N_SWNT.setObjectName("spinBox_chirality_N_SWNT")
        self.spinBox_chirality_M_SWNT = QtWidgets.QSpinBox(self.SWNT)
        self.spinBox_chirality_M_SWNT.setGeometry(QtCore.QRect(147, 10, 51, 31))
        self.spinBox_chirality_M_SWNT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_chirality_M_SWNT.setProperty("value", 1)
        self.spinBox_chirality_M_SWNT.setObjectName("spinBox_chirality_M_SWNT")
        self.spinBox_repeat_units_SWNT = QtWidgets.QSpinBox(self.SWNT)
        self.spinBox_repeat_units_SWNT.setGeometry(QtCore.QRect(310, 50, 51, 31))
        self.spinBox_repeat_units_SWNT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_repeat_units_SWNT.setMinimum(1)
        self.spinBox_repeat_units_SWNT.setObjectName("spinBox_repeat_units_SWNT")
        self.pushButton_help_build_SWNT = QtWidgets.QPushButton(self.SWNT)
        self.pushButton_help_build_SWNT.setGeometry(QtCore.QRect(298, 110, 61, 31))
        self.pushButton_help_build_SWNT.setObjectName("pushButton_help_build_SWNT")
        self.Diameter_SWNT = QtWidgets.QLabel(self.SWNT)
        self.Diameter_SWNT.setGeometry(QtCore.QRect(10, 162, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Diameter_SWNT.setFont(font)
        self.Diameter_SWNT.setObjectName("Diameter_SWNT")
        self.lineEdit_diameter_SWNT = QtWidgets.QLineEdit(self.SWNT)
        self.lineEdit_diameter_SWNT.setGeometry(QtCore.QRect(100, 162, 51, 21))
        self.lineEdit_diameter_SWNT.setAcceptDrops(False)
        self.lineEdit_diameter_SWNT.setStyleSheet("")
        self.lineEdit_diameter_SWNT.setFrame(False)
        self.lineEdit_diameter_SWNT.setClearButtonEnabled(True)
        self.lineEdit_diameter_SWNT.setObjectName("lineEdit_diameter_SWNT")
        self.lable_H_termination_SWNT = QtWidgets.QLabel(self.SWNT)
        self.lable_H_termination_SWNT.setGeometry(QtCore.QRect(10, 100, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lable_H_termination_SWNT.setFont(font)
        self.lable_H_termination_SWNT.setObjectName("lable_H_termination_SWNT")
        self.comboBox_H_termination_SWNT = QtWidgets.QComboBox(self.SWNT)
        self.comboBox_H_termination_SWNT.setGeometry(QtCore.QRect(141, 94, 61, 31))
        self.comboBox_H_termination_SWNT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_H_termination_SWNT.setObjectName("comboBox_H_termination_SWNT")
        self.comboBox_H_termination_SWNT.addItem("")
        self.comboBox_H_termination_SWNT.addItem("")
        self.comboBox_H_termination_SWNT.addItem("")
        self.labl_properties_SWNT = QtWidgets.QLabel(self.SWNT)
        self.labl_properties_SWNT.setGeometry(QtCore.QRect(10, 135, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.labl_properties_SWNT.setFont(font)
        self.labl_properties_SWNT.setObjectName("labl_properties_SWNT")
        self.label_length_SWNT = QtWidgets.QLabel(self.SWNT)
        self.label_length_SWNT.setGeometry(QtCore.QRect(157, 162, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_length_SWNT.setFont(font)
        self.label_length_SWNT.setObjectName("label_length_SWNT")
        self.lineEdit_length_SWNT = QtWidgets.QLineEdit(self.SWNT)
        self.lineEdit_length_SWNT.setGeometry(QtCore.QRect(227, 162, 51, 21))
        self.lineEdit_length_SWNT.setAcceptDrops(False)
        self.lineEdit_length_SWNT.setStyleSheet("")
        self.lineEdit_length_SWNT.setFrame(False)
        self.lineEdit_length_SWNT.setClearButtonEnabled(True)
        self.lineEdit_length_SWNT.setObjectName("lineEdit_length_SWNT")
        self.verticalLayout.addWidget(self.SWNT)

        self.retranslateUi(Form_SWNT)
        QtCore.QMetaObject.connectSlotsByName(Form_SWNT)

    def retranslateUi(self, Form_SWNT):
        _translate = QtCore.QCoreApplication.translate
        Form_SWNT.setWindowTitle(_translate("Form_SWNT", "Form"))
        self.label_chirality_N_SWNT.setText(_translate("Form_SWNT", "N:"))
        self.label_repeat_units_SWNT.setText(_translate("Form_SWNT", "Repeat units:"))
        self.label_bond_length_SWNT.setText(_translate("Form_SWNT", "Bond length (Å):"))
        self.label_type_SWNT.setText(_translate("Form_SWNT", "Type:"))
        self.comboBox_type_SWNT.setItemText(0, _translate("Form_SWNT", "C - C"))
        self.comboBox_type_SWNT.setItemText(1, _translate("Form_SWNT", "B - N"))
        self.comboBox_type_SWNT.setItemText(2, _translate("Form_SWNT", "Ga - N"))
        self.comboBox_type_SWNT.setItemText(3, _translate("Form_SWNT", "Al - N"))
        self.comboBox_type_SWNT.setItemText(4, _translate("Form_SWNT", "Al - P"))
        self.comboBox_type_SWNT.setItemText(5, _translate("Form_SWNT", "Ga - P"))
        self.pushButton_build_SWNT.setText(_translate("Form_SWNT", "Build"))
        self.label_chirality_M_SWNT.setText(_translate("Form_SWNT", "M:"))
        self.pushButton_help_build_SWNT.setText(_translate("Form_SWNT", "Help"))
        self.Diameter_SWNT.setText(_translate("Form_SWNT", "Diameter (Å):"))
        self.lable_H_termination_SWNT.setText(_translate("Form_SWNT", "Hydrogen termination:"))
        self.comboBox_H_termination_SWNT.setItemText(0, _translate("Form_SWNT", "None"))
        self.comboBox_H_termination_SWNT.setItemText(1, _translate("Form_SWNT", "One ends"))
        self.comboBox_H_termination_SWNT.setItemText(2, _translate("Form_SWNT", "Both ends"))
        self.labl_properties_SWNT.setText(_translate("Form_SWNT", "Nanotube properties"))
        self.label_length_SWNT.setText(_translate("Form_SWNT", "Length (Å):"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_SWNT = QtWidgets.QWidget()
    ui = Ui_Form_SWNT()
    ui.setupUi(Form_SWNT)
    Form_SWNT.show()
    sys.exit(app.exec_())

