name: Docs

on:
  push:
    branches: [ master ]
    paths:
      - docs/**
  pull_request:
    branches: [ master ]
    paths:
      - docs/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GH_REF: github.com/nasimanousheh/furious-atoms_website.git
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
          pip install -e git+https://git@github.com/fury-gl/fury@7c8ac640feeb22d4d8bb9d8481d3a49d0a085ef2#egg=fury
      - name: Install FuriousAtoms
        run: pip install .
      - name: Build Docs
        run: cd docs && make -C . html
      - name: Deploy docs
        if: success() && github.ref == 'refs/heads/master'
        run: |
          echo "-- pushing docs --"
          cd docs
          git clone --quiet --branch=main --single-branch https://${GH_REF} gh_pages
          cp -r build/html/* gh_pages/
          cd gh_pages
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action Bot"
          git add .
          git commit -m "Deployed to GitHub Pages / Update documentation" -a || true
          git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" main > /dev/null 2>&1
          echo "-- Deployment done --"

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      # - name: Setup tmate session
      #   if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3

